name: vitssm

channels:
- conda-forge
- nvidia
- pytorch

dependencies:
- python=3.12
- matplotlib
- pandas
- jupyter
- torchmetrics
- #install pytorch and torchvision manually to make cuda work

- pip:
    -av
    - wandb
    - addict
    - omegaconf
    - ruff

