name: vitssm

channels:
- conda-forge
- nvidia
- pytorch

dependencies:
- python=3.12
- ffmpeg
- matplotlib
- pandas
- #install pytorch and torchvision manually to make cuda work

- pip:
    - wandb
    - addict
    - kappaconfig
    - ruff

