version: "3"

env:
    CONDA: micromamba

vars:
    PROJECT: ContVidPred
    LIBRARY: vitssm
    REPOSITORY: https://github.com/davidkuernsteiner/ContVidPred.git
    DATA_DIR: data_store
    CHECKPOINT_DIR: checkpoints
    SCRIPTS_DIR: scripts

tasks:
    env-create:
        cmds:
            - $CONDA env create --file env.yml --yes
            - $CONDA run -n {{.LIBRARY}} pip install -U xformers --index-url https://download.pytorch.org/whl/cu121
            - $CONDA run -n {{.LIBRARY}} pip install -e .

    env-remove:
        cmd: $CONDA env remove -n {{.LIBRARY}} --yes
