project: 'ViTSSM'
group: 'DIT'
name: 'vmdsprites-DiT_T_1-VAE-16'
tags: ['dit', 'vmdsprites', 'tiny', 'ema']
log_freq: 50
eval_freq: 20
checkpoint_freq: 9999999999999
seed: 420

dataset:
  name: 'vmdsprites-nextframe'
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  num_frames: 5
  context_length: 4
  frame_interval: 1
  resolution: 32
  train_percentage: 0.90
  num_workers: 8
  pin_memory: True
  batch_size: 128
  val_batch_size: 64
  rollout_length: 16

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.0001,
             weight_decay: 0.01}
  scheduler:
    name: 'LambdaLR'
    kwargs: {warmup_steps: 1000,
             decay_steps: 9000,
             gamma: 0.1}
    step_on_batch: True
  #scheduler:
  #  name: 'StepLR'
  #  kwargs: {step_size: 1, gamma: 1.0}
  #  step_on_batch: False
  steps: 10000

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}

model:
  name: 'dit'
  device: 'cuda'
  use_amp: False
  use_ema: True
  ema_steps: 1

  vae_type: "vae-tiny"
  vae_checkpoint_path: Null #"/home/david/projects/ViTSSM/checkpoints/ViTSSM/VAE/mdsprites-vae-tiny-16-schedule-small-beta.pth"
  latent_scale_factor: 0.18215
  dit_type: "DiT_T_1"
  dit_kwargs: {
    in_channels: 15,
    out_channels: 3,
    num_classes: 0,
    input_size: 16,
  }
  timestep_respacing: ""
  diffusion_steps: 100