project: 'ViTSSM'
group: 'DIT'
name: 'vmdsprites-DiT_M_2-32'
tags: ['dit', 'vmdsprites', 'micro', 'ema']
log_freq: 50
eval_freq: 100
checkpoint_freq: 9999999999999
seed: 420

dataset:
  name: 'vmdsprites-nextframe'
  load_in_memory: True
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  num_frames: 5
  context_length: 4
  frame_interval: 1
  resolution: 32
  train_percentage: 1.0
  num_workers: 8
  persistent_workers: True
  pin_memory: True
  batch_size: 64
  val_batch_size: 64
  rollout_length: 16

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.0001,
             weight_decay: 0.01}
  scheduler:
    name: 'LambdaLR'
    kwargs: {warmup_steps: 5000,
             decay_steps: 95000,
             gamma: 1.0}
    step_on_batch: True
  #scheduler:
  #  name: 'StepLR'
  #  kwargs: {step_size: 1, gamma: 1.0}
  #  step_on_batch: False
  steps: 100000

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}

model:
  name: 'dit'
  device: 'cuda'
  use_amp: False
  use_ema: False
  ema_steps: 1

  vae_type: "vae-tiny"
  vae_checkpoint_path: Null
  dit_type: "DiT_M_2"
  dit_kwargs: {
    input_size: 32,
    in_channels: 15,
    out_channels: 3,
  }
  diffusion_steps: 1000
  timestep_respacing: "trailing25"
  predict_target: "velocity"
  rescale_betas_zero_snr: True