project: 'ContVidPred'
group: 'DIT'
name: 'vmdsprites-0-DiT_T_2-32'
id: 'vmdsprites-0-DiT_T_2-32_20241222_0'
tags: ['dit', 'vmdsprites', 'tiny']
log_freq: 100
eval_freq: 1
checkpoint_freq: 1000
seed: 0
resume: False

dataset:
  name: 'vmdsprites-nextframe'
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  video_length: 108
  clip_length: 5
  context_length: 4
  rollout_length: 32
  frame_interval: 1
  resolution: 32
  train_percentage: 1.0
  num_workers: 2
  persistent_workers: False
  pin_memory: False
  batch_size: 64
  val_batch_size: 32

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'warm_cos_decay_scheduler'
    kwargs: {warmup_steps: 0,
             decay_steps: 100000,
             gamma: 0.0}
    step_on_batch: True
  #scheduler:
  #  name: 'StepLR'
  #  kwargs: {step_size: 1, gamma: 1.0}
  #  step_on_batch: False
  steps: 100000

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}

model:
  name: 'dit'
  device: 'cuda'
  use_amp: False
  use_ema: False
  ema_steps: 1

  vae_type: "vae-tiny"
  vae_checkpoint_path: Null
  dit_type: "DiT_T_2"
  dit_kwargs: {
    input_size: 32,
    in_channels: 15,
    out_channels: 3,
  }
  diffusion_steps: 1000
  timestep_respacing: "trailing25"
  predict_target: "velocity"
  rescale_betas_zero_snr: True