root_dir: "./"

experiment:
  wandb:
    project: "ViTSSM"
    #group: "ViT"
    #name: "ucf101"

  log_freq: 25
  checkpoint_path: "checkpoints"

dataset:
  root: "data"
  name: "ucf101"
  mode: "train"
  frames_per_clip: 150
  step_between_clips: 150
  resolution: 64
  train_percentage: 0.90
  num_workers: 12
  pin_memory: True

optimization:
  loss:
    name: "MSELoss"
    args: {}
  optimizer:
    name: "AdamW"
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: "StepLR"
    kwargs: {step_size: 1,
             gamma: 0.5}
  epochs: 10
  batch_size: 256
  val_batch_size: 1024

metrics:

model:
  device: "cuda"
  use_amp: True