project: 'ViTSSM'
group: 'LATTE'
name: 'vmdsprites-latte-tiny'
tags: ['latte', 'vmdsprites', 'tiny', 'ema']
log_freq: 25
seed: 420

dataset:
  name: 'vmdsprites'
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  frame_skip: 1
  num_frames: 10
  resolution: 16
  train_percentage: 0.90
  num_workers: 0
  pin_memory: True
  batch_size: 32
  val_batch_size: 32

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'StepLR'
    kwargs: {step_size: 1,
             gamma: 0.75}
  epochs: 10

model:
  name: 'video-vae'
  device: 'cuda'
  use_amp: True
  use_ema: True
  ema_steps: 1
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D"]
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [16, 16]
  layers_per_block: 2
  act_fn: "silu"
  latent_channels: 4
  norm_num_groups: 4