project: "ViTSSM"
group: "ViT"
name: "vmdsprites"
log_freq: 25
seed: 420

dataset:
  name: "vmdsprites"
  mode: "train"
  fold: "0"
  resolution: 64
  train_percentage: 0.90
  num_workers: 0
  pin_memory: True
  batch_size: 32
  val_batch_size: 32

optimization:
  loss:
    name: "MSELoss"
    args: {}
  optimizer:
    name: "AdamW"
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: "StepLR"
    kwargs: {step_size: 1,
             gamma: 0.5}
  epochs: 10

metrics:
  MSE:
    name: "MeanSquaredError"
    kwargs: {}

model:
  name: "latent_nextframe_attention"
  device: "cuda"
  use_amp: True
  frame_in_size: [64, 64]
  latent_dim: 64
  n_frames: 99