experiment:
  project: "ViTSSM"
  group: "ViT"
  name: "vmdsprites"
  log_freq: 25

dataset:
  name: "vmdsprites"
  mode: "train"
  fold: "0"
  resolution: 64
  train_percentage: 0.90
  num_workers: 6
  pin_memory: True

optimization:
  loss:
    name: "MSELoss"
    args: {}
  optimizer:
    name: "AdamW"
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: "StepLR"
    kwargs: {step_size: 1,
             gamma: 0.5}
  epochs: 10
  batch_size: 32
  val_batch_size: 32

metrics:

model:
  device: "cuda"
  use_amp: True