project: 'ViTSSM'
group: 'ViT'
name: 'vmdsprites'
log_freq: 25
seed: 420

dataset:
  name: 'vmdsprites'
  mode: 'train'
  fold: '0'
  resolution: 16
  train_percentage: 0.90
  num_workers: 0
  pin_memory: True
  batch_size: 32
  val_batch_size: 32

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'StepLR'
    kwargs: {step_size: 1,
             gamma: 0.5}
  epochs: 10

metrics:
  MSE:
    name: 'MeanSquaredError'

model:
  name: 'lnfp-simple'
  device: 'cuda'
  use_amp: True
  frame_in_size: [16, 16]
  frame_out_size: [16, 16]
  n_frames: 10
  patch_size: 1
  latent_dim: 32
  n_blocks_encoder: 2
  n_heads_encoder: 1
  n_blocks_latent_predictor: 2
  n_heads_latent_predictor: 1
  n_blocks_decoder: 2
  n_heads_decoder: 1
  mlp_multiplier: 2
  pos_enc_dropout: 0.0
  residual_dropout: 0.0
  mlp_dropout: 0.0