project: 'ContVidPred'
group: 'SRNO'
name: 'vmdsprites-0-SRNO-EDSR'
id: 'vmdsprites-0-SRNO-EDSR_20241222_0'
tags: ['srno', 'vmdsprites', 'baseline']
log_freq: 50
eval_freq: 1
checkpoint_freq: 1000
seed: 0
resume: False

dataset:
  name: 'vmdsprites-srno'
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  video_length: 108
  resolution: 128
  resolution_x: 32
  min_rescale_factor: 1
  max_rescale_factor: 4
  train_percentage: 1.0
  num_workers: 2
  persistent_workers: False
  pin_memory: False
  batch_size: 64
  val_batch_size: 64

optimization:
  loss:
    name: 'L1Loss'
    kwargs: {}
  optimizer:
    name: 'Adam'
    kwargs: {lr: 0.0004}
  scheduler:
    name: 'warm_cos_decay_scheduler'
    kwargs: {warmup_steps: 5000,
             decay_steps: 95000,
             gamma: 0.0}
    step_on_batch: True
  steps: 100000

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}

model:
  name: 'srno'
  device: 'cuda'
  use_amp: False
  use_ema: False
  ema_steps: 1

  width: 256
  blocks: 16