project: 'ContVidPred'
group: 'SRNO'
name: 'vmdsprites-0-SRNO-EDSR'
id: 'vmdsprites-0-SRNO-EDSR_20241221'
resume: False
tags: ['srno', 'vmdsprites', 'baseline']
log_freq: 50
eval_freq: 1
checkpoint_freq: 9999999999999
seed: 0

dataset:
  name: 'vmdsprites-srno'
  load_in_memory: False
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  resolution: 128
  resolution_x: 32
  min_rescale_factor: 1
  max_rescale_factor: 4
  train_percentage: 1.0
  num_workers: 8
  persistent_workers: True
  pin_memory: True
  batch_size: 64
  val_batch_size: 64

optimization:
  loss:
    name: 'L1Loss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'warm_cos_decay_scheduler'
    kwargs: {warmup_steps: 1,
             decay_steps: 99999,
             gamma: 0.0}
    step_on_batch: True
  steps: 100000

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}

model:
  name: 'srno'
  device: 'cuda'
  use_amp: False
  use_ema: False
  ema_steps: 1

  width: 256
  blocks: 16