project: 'ViTSSM'
group: 'VAE'
name: 'mdsprites-vae-tiny-32-schedule-beta-5e-4'
tags: ['vae', 'vmdsprites', 'tiny', 'ema']
log_freq: 50
checkpoint_freq: 99999999999
seed: 420

dataset:
  name: 'mdsprites-ae'
  mode: 'train'
  fold: '0'
  resolution: 32
  train_percentage: 0.90
  num_workers: 12
  pin_memory: True
  batch_size: 32
  val_batch_size: 32

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'LambdaLR'
    kwargs: {warmup_steps: 5000,
             decay_steps: 45000}
    step_on_batch: True
  steps: 50000

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}
#  LPIPS:
#    name: 'LearnedPerceptualImagePatchSimilarity'
#    kwargs: {}

model:
  name: 'vae'
  device: 'cuda'
  use_amp: False
  use_ema: True
  ema_steps: 1
  use_beta_schedule: True
  beta: 0.0005
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D"]
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [16, 16]
  layers_per_block: 2
  act_fn: "silu"
  latent_channels: 4
  norm_num_groups: 8