project: 'ViTSSM'
group: 'VAE'
name: 'mdsprites-vae-small-64'
tags: ['vae', 'vmdsprites', 'small', 'ema']
log_freq: 50
checkpoint_freq: 99999999999
seed: 420

dataset:
  name: 'mdsprites-ae'
  mode: 'train'
  fold: '0'
  resolution: 64
  train_percentage: 0.90
  num_workers: 8
  pin_memory: True
  batch_size: 64
  val_batch_size: 64

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'StepLR'
    kwargs: {step_size: 1,
             gamma: 0.95}
  epochs: 100

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}
  LPIPS:
    name: 'LearnedPerceptualImagePatchSimilarity'
    kwargs: {}

model:
  name: 'vae'
  device: 'cuda'
  use_amp: True
  use_ema: True
  ema_steps: 1
  beta: 0.001
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [32, 32, 32]
  layers_per_block: 2
  act_fn: "silu"
  latent_channels: 4
  norm_num_groups: 4