project: 'ViTSSM'
group: 'VAE'
name: 'ucf101-vae-tiny-32'
tags: ['vae', 'ucf101', 'tiny', 'ema']
log_freq: 100
seed: 420

dataset:
  name: 'ucf101'
  mode: 'train'
  fold: '0'
  output_format: 'TCHW'
  frames_per_clip: 100
  steps_between_clips: 100
  resolution: 32
  train_percentage: 0.90
  num_workers: 8
  pin_memory: True
  batch_size: 5
  val_batch_size: 5

optimization:
  loss:
    name: 'MSELoss'
    kwargs: {}
  optimizer:
    name: 'AdamW'
    kwargs: {lr: 0.001,
             weight_decay: 0.01}
  scheduler:
    name: 'StepLR'
    kwargs: {step_size: 1,
             gamma: 0.75}
  epochs: 10

metrics:
  SSIM:
    name: 'StructuralSimilarityIndexMeasure'
    kwargs: {}
  PSNR:
    name: 'PeakSignalNoiseRatio'
    kwargs: {}

model:
  name: 'video-vae'
  device: 'cuda'
  use_amp: True
  use_ema: True
  ema_steps: 1
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D"]
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [16, 16]
  layers_per_block: 2
  act_fn: "silu"
  latent_channels: 4
  norm_num_groups: 4